# Generated by Django 5.2 on 2025-05-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
