# Generated by Django 5.2 on 2025-05-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_article_companyinfo_employee_promocode_term_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='parking_place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='auto.parkingplace'),
            preserve_default=False,
        ),
    ]
